PRAGMA encoding = "UTF-8";
PRAGMA foreign_keys = ON;
INSERT INTO "preguntas" VALUES(1,'Definiciones','Vehículo es todo aparato...');
INSERT INTO "preguntas" VALUES(2,'Definiciones','Los ciclomotores, ¿tienen la consideración de vehículos de motor?');
INSERT INTO "preguntas" VALUES(3,'Definiciones','El automóvil es un vehículo de motor que sirve normalmente...');
INSERT INTO "preguntas" VALUES(4,'Definiciones','Un ciclomotor de dos ruedas es un vehículo con motor de cilindrada...');
INSERT INTO "preguntas" VALUES(5,'Definiciones','Desde el punto de vista de la circulación, ¿es una motocicleta un automóvil?');
INSERT INTO "preguntas" VALUES(6,'Definiciones','Se define como motocicleta al automóvil...');
INSERT INTO "preguntas" VALUES(7,'Definiciones','Se considera conductor a la persona...');
INSERT INTO "preguntas" VALUES(8,'Definiciones','Peatón es la persona...');
INSERT INTO "preguntas" VALUES(9,'Definiciones','La masa en carga es...');
INSERT INTO "preguntas" VALUES(10,'Definiciones','La masa máxima para la utilización de un vehículo con carga en circulación por las vías públicas es...');
INSERT INTO "preguntas" VALUES(11,'Documentación','¿Qué documentos debe llevar consigo el conductor de una motocicleta, además del permiso de conducción?');
INSERT INTO "preguntas" VALUES(12,'Documentación','Conducir, con un permiso de la clase B, un turismo que arrastra un remolque ligero, ¿está permitido?');
INSERT INTO "preguntas" VALUES(13,'Documentación','Con el permiso B, ¿está permitido conducir un taxi en servicio?');
INSERT INTO "preguntas" VALUES(14,'Documentación','Si tiene supermiso B desde hace más de un año, y ahora obtiene el de clase A2, ¿está obligado a llevar una placa L en su motocicleta?');
INSERT INTO "preguntas" VALUES(15,'Documentación','En un turismo, ¿dónde debe colocar la placa "L" un conductor novel?');
INSERT INTO "preguntas" VALUES(16,'Documentación','La vigencia del permiso de conducción, ¿está condicionada a que su titular no haya perdido su asignación total de puntos?');
INSERT INTO "preguntas" VALUES(17,'Documentación','¿Cuándo debe pasar un turismo la primera inspección técnica?');
INSERT INTO "preguntas" VALUES(18,'Documentación','Si el resultado de la inspección  realizada a su vehículo en una estación ITV es desfavorable, ¿podrá circular por las vías públicas?');
INSERT INTO "preguntas" VALUES(19,'Documentación','Para que pueda circular un ciclomotor, ¿es obligatorio que esté asegurado?');
INSERT INTO "preguntas" VALUES(20,'Documentación','El seguro obligatorio, ¿cubre los daños en la persona del conductor del vehículo asegurado?');
INSERT INTO "preguntas" VALUES(21,'El conductor','Las condiciones psicofísicas del coductor, ¿pueden influir en la capacidad de reacción?');
INSERT INTO "preguntas" VALUES(22,'El conductor','Se denomina tiempo de reacción...');
INSERT INTO "preguntas" VALUES(23,'El conductor','El consumo de drogas, ¿mejora en algún caso el tiempo de reacción?');
INSERT INTO "preguntas" VALUES(24,'El conductor','Las distracciones al volante...');
INSERT INTO "preguntas" VALUES(25,'El conductor','Las distracciones pueden estar originadas...');
INSERT INTO "preguntas" VALUES(26,'El conductor','La vía, su entorno y el propio vehículo, ¿pueden favorecer la aparición de distracciones al volante?');
INSERT INTO "preguntas" VALUES(27,'El conductor','Los accidentes debidos a distracciones suceden más...');
INSERT INTO "preguntas" VALUES(28,'El conductor','Fumar mientras se conduce, ¿puede producir distracciones?');
INSERT INTO "preguntas" VALUES(29,'El conductor','El accidente más frecuente por el usodel teléfono móvil, mientras se conduce, es...');
INSERT INTO "preguntas" VALUES(30,'El conductor','¿Qué circunstancias favorecen la aparición de la fatiga?');
INSERT INTO "preguntas" VALUES(31,'El conductor','Un conductor novel, ¿puede sentirse fatigado más fácilmente?');
INSERT INTO "preguntas" VALUES(32,'El conductor','¿Puede sentir suelo conduciendo aunque haya dormido suficiente?');
INSERT INTO "preguntas" VALUES(33,'El conductor','Como norma general, está prohibido conducir turismos con una tasa de alcohol superior a...');
INSERT INTO "preguntas" VALUES(34,'El conductor','A los conductores noveles se les applica una tasa de alcoholemia menor...');
INSERT INTO "preguntas" VALUES(35,'El conductor','Uno de los efectos que algunas drogas pueden producir en el conductor es...');
INSERT INTO "preguntas" VALUES(36,'El conductor','En un control preventivo, ¿pueden los agentes someter a un conductor a una prueba de detección de estupefacientes?');
INSERT INTO "preguntas" VALUES(37,'El conductor','Si padece una enfermedad crónica, ¿cómo puede reducir el riesgo de accidentes?');
INSERT INTO "preguntas" VALUES(38,'El conductor','¿Qué debe hacer si está en estado de estrés?');
INSERT INTO "preguntas" VALUES(39,'El conductor','Si está tomando medicamentos y va a conducir...');
INSERT INTO "preguntas" VALUES(40,'El conductor','Para los conductores y pasajeros de motocicletas, ¿tiene importancia el vestuario a utilizar?');
INSERT INTO "respuestas" VALUES(1,'que está en la vía pública.',0,1);
INSERT INTO "respuestas" VALUES(2,'apto para circular por las vías pública.',1,1);
INSERT INTO "respuestas" VALUES(3,'que tiene un motor.',0,1);
INSERT INTO "respuestas" VALUES(4,'No.',0,2);
INSERT INTO "respuestas" VALUES(5,'Si, pero solo los de cuatro ruedas.',1,2);
INSERT INTO "respuestas" VALUES(6,'Si, porque están provistos de un motor.',0,2);
INSERT INTO "respuestas" VALUES(7,'para la realización de trabajos agrícolas.',0,3);
INSERT INTO "respuestas" VALUES(8,'para transportar personas o cosas o ambas a la vez, o para la tracción de otros vehículos con ese fin.',1,3);
INSERT INTO "respuestas" VALUES(9,'para realizar obras o determinados servicios.',0,3);
INSERT INTO "respuestas" VALUES(10,'no superior a 50 centímetros cúbicos si es de combustión interna.',0,4);
INSERT INTO "respuestas" VALUES(11,'no superior a 50 centímetros cúbicos y una velocidad máxima no superior a 45 km/h.',1,4);
INSERT INTO "respuestas" VALUES(12,'inferior a 50 centímetros cúbicos.',0,4);
INSERT INTO "respuestas" VALUES(13,'No, porque los automóviles son turismos.',0,5);
INSERT INTO "respuestas" VALUES(14,'Si.',1,5);
INSERT INTO "respuestas" VALUES(15,'Si, porque es un vehículo que se mueve por si mismo.',0,5);
INSERT INTO "respuestas" VALUES(16,'de dos o tres ruedas con una cilindrada superior a 50 centímetros cúbicos.',0,6);
INSERT INTO "respuestas" VALUES(17,'de dos ruedas con un motor de cilindrada superior a 50 centímetros cúbicos, y/o con una velocidad máxima superior a 45 km/h.',1,6);
INSERT INTO "respuestas" VALUES(18,'con una cilindrada superior a 125 centímetros cúbicos.',0,6);
INSERT INTO "respuestas" VALUES(19,'que maneja el mecanismo de dirección o va al mando de un vehículo.',1,7);
INSERT INTO "respuestas" VALUES(20,'que maneja el volante de un vehículo cuando circula en prácticas.',0,7);
INSERT INTO "respuestas" VALUES(21,'que conduce a pie un ciclo o ciclomotor de dos ruedas.',0,7);
INSERT INTO "respuestas" VALUES(22,'que conduce a pie un vehículo de dos ruedas.',0,8);
INSERT INTO "respuestas" VALUES(23,'a cuyo cargo está un animal o animales.',0,8);
INSERT INTO "respuestas" VALUES(24,'que, sin ser conductor transita a pie por las vías públicas.',1,8);
INSERT INTO "respuestas" VALUES(25,'la masa efectiva del vehículo, sin incluír la masa del personal de servicio ni de los pasajeros.',0,9);
INSERT INTO "respuestas" VALUES(26,'la masa máxima autorizada para la utilización del vehículo.',0,9);
INSERT INTO "respuestas" VALUES(27,'la masa efectiva del vehículo y de su carga.',1,9);
INSERT INTO "respuestas" VALUES(28,'la tara.',0,10);
INSERT INTO "respuestas" VALUES(29,'la masa en carga.',0,10);
INSERT INTO "respuestas" VALUES(30,'la masa máxima autorizada.',1,10);
INSERT INTO "respuestas" VALUES(31,'La tarjeta ITV y el permiso de circulación.',1,11);
INSERT INTO "respuestas" VALUES(32,'El permiso de circulación, solamente.',0,11);
INSERT INTO "respuestas" VALUES(33,'La tarjeta ITV, sólamente.',0,11);
INSERT INTO "respuestas" VALUES(34,'Solo si la masa máxima autorizada del conjunto no supera los 3.500 kilogramos.',0,12);
INSERT INTO "respuestas" VALUES(35,'Sí, si el turismo se puede conducir con el permiso de la clase B.',1,12);
INSERT INTO "respuestas" VALUES(36,'No, en ningún caso.',0,12);
INSERT INTO "respuestas" VALUES(37,'No, es necesario tener, además, el permiso BTP.',1,13);
INSERT INTO "respuestas" VALUES(38,'En vías urbanas sí, en vías interurbanas no.',0,13);
INSERT INTO "respuestas" VALUES(39,'No, es necesario el permiso de la clase C1.',0,13);
INSERT INTO "respuestas" VALUES(40,'Si durante un año, en la parte trasera.',0,14);
INSERT INTO "respuestas" VALUES(41,'No',1,14);
INSERT INTO "respuestas" VALUES(42,'Si, en la parte delantera, durante un año.',0,14);
INSERT INTO "respuestas" VALUES(43,'En un lugar visible en la parte posterior izquierda.',1,15);
INSERT INTO "respuestas" VALUES(44,'En un lugar visible en la parte posterior derecha.',0,15);
INSERT INTO "respuestas" VALUES(45,'En cualquier lugar visible de la parte posterior.',0,15);
INSERT INTO "respuestas" VALUES(46,'No, su vigencia sólo está limitada en el tiempo.',0,16);
INSERT INTO "respuestas" VALUES(47,'No, los puntos solo afectan a las sanciones impuestas.',0,16);
INSERT INTO "respuestas" VALUES(48,'Sí.',1,16);
INSERT INTO "respuestas" VALUES(49,'A los 3 años, a partir de la fecha de la primera matriculación.',0,17);
INSERT INTO "respuestas" VALUES(50,'A los 4 años, a partir de la fecha de fabricación o importación.',0,17);
INSERT INTO "respuestas" VALUES(51,'A los 4 años, a partir de la fecha de la primera matriculación.',1,17);
INSERT INTO "respuestas" VALUES(52,'Sí, si el defecto observado no impide la marcha del vehículo.',0,18);
INSERT INTO "respuestas" VALUES(53,'No, en absoluto, porque el vehículo causará baja definitiva.',0,18);
INSERT INTO "respuestas" VALUES(54,'No, salvo para su traslado al taller y la vuelta a la ITV para nueva inspección.',1,18);
INSERT INTO "respuestas" VALUES(55,'Sí, pero solamente los que tienen más de dos ruedas.',0,19);
INSERT INTO "respuestas" VALUES(56,'No.',0,19);
INSERT INTO "respuestas" VALUES(57,'Sí.',1,19);
INSERT INTO "respuestas" VALUES(58,'No.',1,20);
INSERT INTO "respuestas" VALUES(59,'Sí, salvo cuando el conductor es el tomador del seguro.',0,20);
INSERT INTO "respuestas" VALUES(60,'Sí, en todo caso.',0,20);
INSERT INTO "respuestas" VALUES(61,'Depende de la situación.',0,21);
INSERT INTO "respuestas" VALUES(62,'No.',0,21);
INSERT INTO "respuestas" VALUES(63,'Sí.',1,21);
INSERT INTO "respuestas" VALUES(64,'al tiempo que transcurre desde que el conductor ve un peligro hasta que responde al mismo.',1,22);
INSERT INTO "respuestas" VALUES(65,'al tiempo que tarda en detenerse el vehículo con el freno accionado.',0,22);
INSERT INTO "respuestas" VALUES(66,'al tiempo que transcurre desde que el conductor observa un peligro hasta que se detiene el vehículo.',0,22);
INSERT INTO "respuestas" VALUES(67,'Sí, en algunos casos disminuyéndolo.',0,23);
INSERT INTO "respuestas" VALUES(68,'Sí, con la cocaína.',0,23);
INSERT INTO "respuestas" VALUES(69,'No, en ningún caso.',1,23);
INSERT INTO "respuestas" VALUES(70,'no causan accidentes.',0,24);
INSERT INTO "respuestas" VALUES(71,'causan muy pocos accidentes.',0,24);
INSERT INTO "respuestas" VALUES(72,'causan una gran cantidad de accidentes.',1,24);
INSERT INTO "respuestas" VALUES(73,'sólo por elementos externos al vehículo.',0,25);
INSERT INTO "respuestas" VALUES(74,'tanto por elementos externos al vehículo como por los elementos internos.',1,25);
INSERT INTO "respuestas" VALUES(75,'únicamente por elementos internos del vehículo.',0,25);
INSERT INTO "respuestas" VALUES(76,'Sí, el vehículo y la vía pero no su entorno.',0,26);
INSERT INTO "respuestas" VALUES(77,'Sí.',1,26);
INSERT INTO "respuestas" VALUES(78,'Sí, la vía pero no su entorno.',0,26);
INSERT INTO "respuestas" VALUES(79,'durante la tarde.',0,27);
INSERT INTO "respuestas" VALUES(80,'durante el día y los fines de semana.',1,27);
INSERT INTO "respuestas" VALUES(81,'en los meses de invierno.',0,27);
INSERT INTO "respuestas" VALUES(82,'No, si se tiene cuidado.',0,28);
INSERT INTO "respuestas" VALUES(83,'Sí.',1,28);
INSERT INTO "respuestas" VALUES(84,'No, en ningún caso.',0,28);
INSERT INTO "respuestas" VALUES(85,'el choque frontolateral.',0,29);
INSERT INTO "respuestas" VALUES(86,'el alcance.',0,29);
INSERT INTO "respuestas" VALUES(87,'la salida de la vía.',1,29);
INSERT INTO "respuestas" VALUES(88,'Conducir con poco tráfico, porque exige mayor concentración.',0,30);
INSERT INTO "respuestas" VALUES(89,'Mantener en el interior del vehículo una temperatura elevada, porque puede afectar al estado psicofísico.',1,30);
INSERT INTO "respuestas" VALUES(90,'Que el recorrido sea por una vía muy conocida.',0,30);
INSERT INTO "respuestas" VALUES(91,'Únicamente cuando sea una persona mayor.',0,31);
INSERT INTO "respuestas" VALUES(92,'No.',0,31);
INSERT INTO "respuestas" VALUES(93,'Sí, por la falta de experiencia al volante.',1,31);
INSERT INTO "respuestas" VALUES(94,'Sí, en las primeras horas de la noche.',0,32);
INSERT INTO "respuestas" VALUES(95,'Sí, especialmente en horas de madrugada y las primeras horas de la tarde.',1,32);
INSERT INTO "respuestas" VALUES(96,'No.',0,32);
INSERT INTO "respuestas" VALUES(97,'0,5 gramos de alcohol por litro de sangre.',1,33);
INSERT INTO "respuestas" VALUES(98,'0,8 gramos de alcohol por litro de sangre.',0,33);
INSERT INTO "respuestas" VALUES(99,'0,3 gramos por litro de sangre.',0,33);
INSERT INTO "respuestas" VALUES(100,'porque en ellos los efectos del alcohol son menores.',0,34);
INSERT INTO "respuestas" VALUES(101,'porque carecen de la suficiente experiencia en la conducción.',1,34);
INSERT INTO "respuestas" VALUES(102,'únicamente porque las normas de tráfico lo imponen.',0,34);
INSERT INTO "respuestas" VALUES(103,'la ampliación del campo visual.',0,35);
INSERT INTO "respuestas" VALUES(104,'la incorrecta percepción del tiempo y del espacio.',1,35);
INSERT INTO "respuestas" VALUES(105,'la disminución de la distancia de detención.',0,35);
INSERT INTO "respuestas" VALUES(106,'No, este tipo de pruebas sólo se pueden realizar en un centro médico.',0,36);
INSERT INTO "respuestas" VALUES(107,'No, solamente si está implicado en un accidente.',0,36);
INSERT INTO "respuestas" VALUES(108,'Sí',1,36);
INSERT INTO "respuestas" VALUES(109,'Evitando situaciones que puedan provocar una crisis.',1,37);
INSERT INTO "respuestas" VALUES(110,'Suspendiendo el tratamiento cuando tenga que conducir.',0,37);
INSERT INTO "respuestas" VALUES(111,'Aumentando la dosis del medicamento cuando tenga que conducir.',0,37);
INSERT INTO "respuestas" VALUES(112,'Evitar conducir.',1,38);
INSERT INTO "respuestas" VALUES(113,'Tomar un estimulante.',0,38);
INSERT INTO "respuestas" VALUES(114,'Tomar un ansiolítico antes de conducir.',0,38);
INSERT INTO "respuestas" VALUES(115,'no es necesario tomar ninguna precaución cuando no se necesita receta médica para poder comprarlos.',0,39);
INSERT INTO "respuestas" VALUES(116,'debe leer las indicaciones del prospecto, y en caso de duda, consultar al médico o farmacéutico.',1,39);
INSERT INTO "respuestas" VALUES(117,'debe esperar al menos dos horas antes de conducir.',0,39);
INSERT INTO "respuestas" VALUES(118,'No, es indiferente siempre que lleven casco.',0,40);
INSERT INTO "respuestas" VALUES(119,'No, porque no aporta nada a la seguridad.',0,40);
INSERT INTO "respuestas" VALUES(120,'Sí, es fundamentel porque el cuerpo está directamente expuesto a las inclemencias del tiempo.',1,40);
